[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO: Upgrade winit once I'm past needing the tutorial.
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.11.5"
log = "0.4"
wgpu = "22.0"
